### ISSUE TITLE
:page_facing_up: 请求添加许可证

### ISSUE THREAD

**Issue by zhulinyv** [maple-flowers/maple-from-fall-and-flower#5]
你好, 我正在开发一个类似于 stable-diffusion-webui 的 NovelAI 量产工具, 它是开源且非盈利的, 这是我的项目地址: [Semi-Auto-NovelAI-to-Pixiv](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv)

它同样支持插件导入, 所以我希望使用 [maple-from-fall-and-flower](https://github.com/maple-flowers/maple-from-fall-and-flower) 移植一个同样或类似的 tag 生成插件在 [Semi-Auto-NovelAI-to-Pixiv](https://github.com/zhulinyv/Semi-Auto-NovelAI-to-Pixiv) 中使用

但您的项目中尚未添加许可证, 我不可以直接修改代码并分发使用, 因此请求添加许可证

**Comment by maple-flowers** [comment]
你好，已经添加啦

**Comment by zhulinyv** [comment]
非常感谢
